"""
Relay Service --- Lightweight WebSocket message relay

Server does zero AI inference, just passthrough:
  Browser WS (/api/learning/ws)  <-->  RelayManager  <-->  Local Agent WS (/api/learning/agent/ws)

Pairing: one-time 8-char code generated by browser, entered by agent. Auto-expires.
"""

import asyncio
import json
import logging
import secrets
import string
from dataclasses import dataclass, field
from typing import Optional
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

AGENT_IDLE_TIMEOUT = 600
BROWSER_IDLE_TIMEOUT = 300
PAIRING_CODE_TTL = 300  # 配对码 5 分钟有效


@dataclass
class BrowserSession:
    ws: any
    pairing_code: str
    message_queue: asyncio.Queue = field(default_factory=asyncio.Queue)
    last_active: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class AgentSession:
    ws: any
    pairing_code: str
    message_queue: asyncio.Queue = field(default_factory=asyncio.Queue)
    last_active: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


class PairingStore:
    """Manage one-time pairing codes"""

    def __init__(self):
        self._codes: dict[str, str] = {}          # code -> code
        self._browser_by_code: dict[str, asyncio.Queue] = {}  # code -> (browser_queue, code_created_at)
        self._code_created: dict[str, datetime] = {}

    def generate(self) -> str:
        """Generate a new 8-char readable code"""
        while True:
            code = "-".join([
                "".join(secrets.choice(string.ascii_uppercase + string.digits) for _ in range(4)),
                "".join(secrets.choice(string.ascii_uppercase + string.digits) for _ in range(4)),
            ])
            if code not in self._codes:
                self._codes[code] = code
                self._code_created[code] = datetime.now(timezone.utc)
                return code

    def claim(self, code: str) -> bool:
        """Agent claims a code. Returns True if valid and unexpired."""
        if code not in self._codes:
            return False
        created = self._code_created.get(code)
        if created and (datetime.now(timezone.utc) - created).total_seconds() > PAIRING_CODE_TTL:
            self._codes.pop(code, None)
            self._code_created.pop(code, None)
            return False
        return True

    def remove(self, code: str):
        self._codes.pop(code, None)
        self._code_created.pop(code, None)

    def cleanup_expired(self):
        now = datetime.now(timezone.utc)
        for code, created in list(self._code_created.items()):
            if (now - created).total_seconds() > PAIRING_CODE_TTL:
                self._codes.pop(code, None)
                self._code_created.pop(code, None)


class RelayManager:
    """Singleton: pair browser and agent by one-time pairing code"""

    def __init__(self):
        self._browsers: dict[str, BrowserSession] = {}
        self._agents: dict[str, AgentSession] = {}
        self._pairing = PairingStore()
        self._cleanup_task: Optional[asyncio.Task] = None

    @property
    def pairing(self) -> PairingStore:
        return self._pairing

    async def start_cleanup(self):
        if self._cleanup_task and not self._cleanup_task.done():
            return
        self._cleanup_task = asyncio.create_task(self._cleanup_loop())

    async def _cleanup_loop(self):
        while True:
            await asyncio.sleep(60)
            now = datetime.now(timezone.utc)
            for code, session in list(self._browsers.items()):
                if (now - session.last_active).total_seconds() > BROWSER_IDLE_TIMEOUT:
                    await self._close_browser(code, "idle timeout")
            for code, session in list(self._agents.items()):
                if (now - session.last_active).total_seconds() > AGENT_IDLE_TIMEOUT:
                    await self._close_agent(code, "idle timeout")
            self._pairing.cleanup_expired()

    async def register_browser(self, ws) -> tuple[str, asyncio.Queue]:
        """Browser connects, get a new pairing code + message queue"""
        code = self._pairing.generate()
        session = BrowserSession(ws=ws, pairing_code=code)
        self._browsers[code] = session
        logger.info(f"Browser connected, pairing code: {code}")
        return code, session.message_queue

    async def register_agent(self, ws, code: str) -> Optional[asyncio.Queue]:
        """Agent connects with a pairing code. Returns queue or None if invalid."""
        if not self._pairing.claim(code):
            return None

        # Check if browser is waiting
        browser = self._browsers.get(code)
        if not browser:
            # Code valid but browser not connected yet — reject
            self._pairing.remove(code)
            return None

        old_agent = self._agents.pop(code, None)
        if old_agent:
            await self._close_ws(old_agent.ws)

        session = AgentSession(ws=ws, pairing_code=code)
        self._agents[code] = session
        self._pairing.remove(code)  # code consumed
        logger.info(f"Agent paired: {code}")

        # Notify browser
        await browser.message_queue.put({"type": "agent_connected"})
        return session.message_queue

    async def browser_to_agent(self, code: str, message: dict) -> bool:
        agent = self._agents.get(code)
        if not agent:
            return False
        agent.last_active = datetime.now(timezone.utc)

        # Inject vector search context for user messages with kp/material IDs
        if message.get("type") == "user_message":
            kp_ids = message.get("kp_ids", []) or []
            mat_ids = message.get("material_ids", []) or []
            text = message.get("text", "")
            if text.strip():
                try:
                    from src.routes.learning_context import ContextRequest, search_vector_context
                    req = ContextRequest(message=text, kp_ids=kp_ids, material_ids=mat_ids)
                    context = await search_vector_context(req)
                    if context:
                        message = dict(message)  # Don't mutate original
                        message["text"] = (
                            "【系统提示：以下是向量数据库检索到的相关学习资料，请直接基于这些内容回答，不要寻找文件】\n\n"
                            + context + "\n\n【以上是参考资料，请基于此回答】\n\n" + text
                        )
                        logger.info("Relay: injected vector context, %d chars", len(context))
                except Exception as e:
                    logger.warning("Relay: context injection failed: %s", e)

        await agent.message_queue.put(message)
        return True

    async def agent_to_browser(self, code: str, message: dict) -> bool:
        browser = self._browsers.get(code)
        if not browser:
            return False
        browser.last_active = datetime.now(timezone.utc)
        await browser.message_queue.put(message)
        return True

    async def remove_browser(self, code: str):
        browser = self._browsers.pop(code, None)
        if browser:
            agent = self._agents.get(code)
            if agent:
                await agent.message_queue.put({"type": "browser_disconnected"})
        logger.info(f"Browser disconnected: code={code}")

    async def remove_agent(self, code: str):
        agent = self._agents.pop(code, None)
        if agent:
            browser = self._browsers.get(code)
            if browser:
                await browser.message_queue.put({"type": "agent_disconnected"})
        logger.info(f"Agent disconnected: code={code}")

    async def _close_browser(self, code: str, reason: str):
        logger.info(f"Closing browser: code={code} reason={reason}")
        session = self._browsers.pop(code, None)
        if session:
            await self._close_ws(session.ws)
            self._pairing.remove(code)

    async def _close_agent(self, code: str, reason: str):
        logger.info(f"Closing agent: code={code} reason={reason}")
        session = self._agents.pop(code, None)
        if session:
            await self._close_ws(session.ws)
            browser = self._browsers.get(code)
            if browser:
                await browser.message_queue.put({
                    "type": "agent_disconnected",
                    "reason": reason,
                })

    @staticmethod
    async def _close_ws(ws) -> None:
        try:
            await ws.close()
        except Exception:
            pass


relay = RelayManager()
